version = 1

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "php"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = [
    "jquery",
    "browser"
  ]

[[analyzers]]
name = "docker"

[[transformers]]
name = "prettier"

[[transformers]]
name = "standardjs"

[[transformers]]
name = "php-cs-fixer"