name: Build

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: build-deploy

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      # - name: Cache Composer dependencies
      #   uses: actions/cache@v4
      #   with:
      #     path: /tmp/composer-cache
      #     key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      # - name: Install dependencies
      #   uses: "php-actions/composer@v6"
      #   with:
      #     php_extensions: sockets
      #     dev: no
      #     progress: yes
      #     working_dir: "./Src/"

      - name: Docker compose up
        run: docker compose up -d

      # - name: Test Requests
      #   id: test_requests
      #   run: |
      #     chmod +x Tests/request-tests.sh
      #     Tests/request-tests.sh "Tests/Requests"

      # - name: Update PR with comment (request tests - failed)
      #   if: failure() && steps.test_requests.outputs.error == 'true'
      #   uses: mshick/add-pr-comment@v2
      #   with:
      #     refresh-message-position: true
      #     message-id: "requests"
      #     message: |
      #       :test_tube: **Request tests summary**

      #       :x: The request tests failed.
      #       ${{ steps.test_requests.outputs.requests_failed }}

      #       <details>
      #         <summary>Last failed response</summary>

      #         ```
      #         ${{ steps.test_requests.outputs.response }}
              
      #         ```
              
      #       </details>

      # - name: Update PR with comment (request tests - succeeded)
      #   if: success()
      #   uses: mshick/add-pr-comment@v2
      #   with:
      #     refresh-message-position: true
      #     message-id: "requests"
      #     message: |
      #       :test_tube: **Request tests summary**

      #       :white_check_mark: All test requests succeeded


